#!/bin/bash

_base_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
source $_base_dir/vendor/github.com/reconquest/import.bash/import.bash

import:use github.com/reconquest/test-runner.bash
import:use github.com/reconquest/vim-tests.bash

_vim_session=vim-test-$RANDOM

test-runner:run "${@}"
